language: node_js
node_js:
  - 14

cache: npm

before_script:
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

script:
  - npm run check
  - npx hardhat test
  - npx codechecks
  - npx hardhat coverage
  - cat coverage/lcov.info | npx coveralls

jobs:
  include:
    - stage: deploy-kovan
    - if: branch = master and env(DEPLOY) = kovan
    - script: npm run deploy:kovan
